modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Jozufozu/Flywheel/issues"
license = "MIT"

[[mods]]
modId = "flywheel"
version = "${file.jarVersion}"
displayName = "Flywheel"
logoFile = "logo.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/flywheel"
updateJSONURL = "https://api.modrinth.com/updates/5lpsZoRi/forge_updates.json"
authors = "Jozufozu"
description = '''
A modern engine for modded minecraft.'''

[[dependencies.flywheel]]
modId = "forge"
mandatory = true
versionRange = "[41.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.flywheel]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "CLIENT"
